2024-12-13 12:04:37.646754+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null,\000d\000a)"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null,\000d\000a)"; expected "identifier"; SQL statement:
create table user(
    user_id     VARCHAR(20)     primary key,
    user_name   VARCHAR(40)     not null,
    mail_address    VARCHAR(256)     not null,
    pass        VARCHAR(20)     not null,
    pass_confirm        VARCHAR(20)     not null,
) [42001-232]
2024-12-13 12:04:50.375193+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; expected "identifier"; SQL statement:
create table user(
    user_id     VARCHAR(20)     primary key,
    user_name   VARCHAR(40)     not null,
    mail_address    VARCHAR(256)     not null,
    pass        VARCHAR(20)     not null,
    pass_confirm        VARCHAR(20)     not null
) [42001-232]
2024-12-13 12:06:42.974904+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; expected "identifier"; SQL statement:
create table user(
    user_id     VARCHAR(20)     primary key,
    user_name   VARCHAR(40)     not null,
    mail_address    VARCHAR(256)     not null,
    pass        VARCHAR(20)     not null,
    pass_confirm        VARCHAR(20)     not null
) [42001-232]
2024-12-13 12:06:44.289119+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table [*]user(\000d\000a    user_id     VARCHAR(20)     primary key,\000d\000a    user_name   VARCHAR(40)     not null,\000d\000a    mail_address    VARCHAR(256)     not null,\000d\000a    pass        VARCHAR(20)     not null,\000d\000a    pass_confirm        VARCHAR(20)     not null\000d\000a)"; expected "identifier"; SQL statement:
create table user(
    user_id     VARCHAR(20)     primary key,
    user_name   VARCHAR(40)     not null,
    mail_address    VARCHAR(256)     not null,
    pass        VARCHAR(20)     not null,
    pass_confirm        VARCHAR(20)     not null
) [42001-232]
2024-12-13 12:21:58.541845+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "USERS_ID" が見つかりません
Column "USERS_ID" not found; SQL statement:
create table post_item (
    post_id         INTEGER     primary key,
    users_id         VARCHAR(20)     references users(users_id),
    post_date       TIMESTAMP,
    caption         TEXT        
) [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:786)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:184)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:219)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:74)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:139)
	at org.h2.command.Command.executeUpdate(Command.java:304)
	at org.h2.command.Command.executeUpdate(Command.java:248)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 12:29:17.217740+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: "CONSTRAINT_1F" が依存しているため、"USERS" をドロップすることはできません
Cannot drop "USERS" because "CONSTRAINT_1F" depends on it; SQL statement:
drop table users [90107-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:108)
	at org.h2.command.ddl.DropTable.update(DropTable.java:133)
	at org.h2.command.CommandContainer.update(CommandContainer.java:139)
	at org.h2.command.Command.executeUpdate(Command.java:304)
	at org.h2.command.Command.executeUpdate(Command.java:248)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 12:34:35.640911+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "alter table users drop mail_address [*]password"
Syntax error in SQL statement "alter table users drop mail_address [*]password"; SQL statement:
alter table users drop mail_address password [42000-232]
2024-12-13 13:38:32.384670+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
insert into post_item (
    values('inu_dog223','2024-12-13 13:45:00','お散歩中です')
) [21002-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:311)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 13:41:22.857794+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into post_item (\000d\000a    values([*]default,'inu_dog223','2024-12-13 13:45:00','お散歩中です')\000d\000a)"; 期待されるステートメント "INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "insert into post_item (\000d\000a    values([*]default,'inu_dog223','2024-12-13 13:45:00','お散歩中です')\000d\000a)"; expected "INTERSECTS (, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
insert into post_item (
    values(default,'inu_dog223','2024-12-13 13:45:00','お散歩中です')
) [42001-232]
2024-12-13 14:01:29.319807+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "STAMP_SOURCE" が見つかりません
Table "STAMP_SOURCE" not found; SQL statement:
insert into stamp_source (stamp_name, stamp_code)
values ('dog face','&#x1f436;') [42102-232]
2024-12-13 14:02:05.403049+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLDataException: データ変換中にエラーが発生しました "'&#x1f436;' (STAMP_SOURCE: ""STAMP_CODE"" INTEGER DEFAULT 'none' NOT NULL)"
Data conversion error converting "'&#x1f436;' (STAMP_SOURCE: ""STAMP_CODE"" INTEGER DEFAULT 'none' NOT NULL)"; SQL statement:
insert into stamp_source (stamp_name, stamp_code)
values ('dog face','&#x1f436;') [22018-232]
2024-12-13 14:03:50.511976+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table stamp_num (\000d\000a    stamp_id         INTEGER,\000d\000a    post_id         INTEGER,\000d\000a    stamp_num         INTEGER   not null,\000d\000a    \000d\000a    foreign key (stamp_id, post_id)\000d\000a        references  post_item(post_id), stamp_source[*](stamp_id) \000d\000a)"; 期待されるステートメント "data type"
Syntax error in SQL statement "create table stamp_num (\000d\000a    stamp_id         INTEGER,\000d\000a    post_id         INTEGER,\000d\000a    stamp_num         INTEGER   not null,\000d\000a    \000d\000a    foreign key (stamp_id, post_id)\000d\000a        references  post_item(post_id), stamp_source[*](stamp_id) \000d\000a)"; expected "data type"; SQL statement:
create table stamp_num (
    stamp_id         INTEGER,
    post_id         INTEGER,
    stamp_num         INTEGER   not null,
    
    foreign key (stamp_id, post_id)
        references  post_item(post_id), stamp_source(stamp_id) 
) [42001-232]
2024-12-13 14:37:00.089713+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "USER_ID" があいまいです
Ambiguous column name "USER_ID"; SQL statement:
select user_name, post_id, caption, post_date
from post_item
join users
on post_item.user_id = user_id [90059-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:197)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:175)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:547)
	at org.h2.table.TableFilter$MapColumnsVisitor.accept(TableFilter.java:1317)
	at org.h2.table.TableFilter.visit(TableFilter.java:1260)
	at org.h2.table.TableFilter.addJoin(TableFilter.java:640)
	at org.h2.command.Parser.addJoin(Parser.java:2375)
	at org.h2.command.Parser.readTableReference(Parser.java:2286)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2702)
	at org.h2.command.Parser.parseSelect(Parser.java:2810)
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2692)
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2547)
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2526)
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2519)
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2512)
	at org.h2.command.Parser.parseQuery(Parser.java:2479)
	at org.h2.command.Parser.parsePrepared(Parser.java:610)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 15:01:22.385853+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "POST_ID" があいまいです
Ambiguous column name "POST_ID"; SQL statement:
select post_id, caption, post_date, stamp_id, stamp_name, stamp_code, stamp_num
from post_item
join stamp_num
on post_item.post_id = stamp_num.post_id
join stamp_source
on stamp_num.stamp_id = stamp_source.stamp_id [90059-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:197)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:175)
	at org.h2.command.query.Select.mapColumns(Select.java:1601)
	at org.h2.command.query.Select.init(Select.java:1158)
	at org.h2.command.Parser.parseQuery(Parser.java:2482)
	at org.h2.command.Parser.parsePrepared(Parser.java:610)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 15:02:01.071720+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "STAMP_ID" があいまいです
Ambiguous column name "STAMP_ID"; SQL statement:
select post_item.post_id, caption, post_date, stamp_id, stamp_name, stamp_code, stamp_num
from post_item
join stamp_num
on post_item.post_id = stamp_num.post_id
join stamp_source
on stamp_num.stamp_id = stamp_source.stamp_id [90059-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:197)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:175)
	at org.h2.command.query.Select.mapColumns(Select.java:1601)
	at org.h2.command.query.Select.init(Select.java:1158)
	at org.h2.command.Parser.parseQuery(Parser.java:2482)
	at org.h2.command.Parser.parsePrepared(Parser.java:610)
	at org.h2.command.Parser.parse(Parser.java:581)
	at org.h2.command.Parser.parse(Parser.java:556)
	at org.h2.command.Parser.prepareCommand(Parser.java:484)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-13 15:42:43.357537+09:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "PHOTO" が見つかりません
Table "PHOTO" not found; SQL statement:
select user_name, U.user_id, Pi.post_id, caption, post_date, picture_id, picture_url
from post_item AS Pi
join users AS U
on Pi.user_id = U.user_id
join photo AS Ph
on Pi.post_id = Ph.post_id [42102-232]
2024-12-16 13:42:26.820437+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; expected "identifier"; SQL statement:
create table stamp_source (
    category_id      INTEGER     generated always as identity primary key,
    category_name    VARCHAR(30) not null default 'other',    
) [42001-232]
2024-12-16 13:42:26.840385+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "CATEGORY__SOURCE" が見つかりません
Table "CATEGORY__SOURCE" not found; SQL statement:
insert into category__source (category_name)
values ('その他')

insert into category__source (category_name)
values ('いぬ')

insert into category__source (category_name)
values ('ねこ')

insert into category__source (category_name)
values ('とり')

insert into category__source (category_name)
values ('ハムスター')

insert into category__source (category_name)
values ('りす')

insert into category__source (category_name)
values ('はちゅうるい')

insert into category__source (category_name)
values ('さかな') [42102-232]
2024-12-16 13:43:18.566122+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; expected "identifier"; SQL statement:
create table stamp_source (
    category_id      INTEGER     generated always as identity primary key,
    category_name    VARCHAR(30) not null default 'other',    
) [42001-232]
2024-12-16 13:43:18.568129+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "CATEGORY_SOURCE" が見つかりません
Table "CATEGORY_SOURCE" not found; SQL statement:
insert into category_source (category_name)
values ('その他')

insert into category_source (category_name)
values ('いぬ')

insert into category_source (category_name)
values ('ねこ')

insert into category_source (category_name)
values ('とり')

insert into category_source (category_name)
values ('ハムスター')

insert into category_source (category_name)
values ('りす')

insert into category_source (category_name)
values ('はちゅうるい')

insert into category_source (category_name)
values ('さかな') [42102-232]
2024-12-16 13:43:19.515725+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; 期待されるステートメント "identifier"
Syntax error in SQL statement "create table stamp_source (\000d\000a    category_id      INTEGER     generated always as identity primary key,\000d\000a    category_name    VARCHAR(30) not null default 'other',    \000d\000a[*])"; expected "identifier"; SQL statement:
create table stamp_source (
    category_id      INTEGER     generated always as identity primary key,
    category_name    VARCHAR(30) not null default 'other',    
) [42001-232]
2024-12-16 13:43:19.517676+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "CATEGORY_SOURCE" が見つかりません
Table "CATEGORY_SOURCE" not found; SQL statement:
insert into category_source (category_name)
values ('その他')

insert into category_source (category_name)
values ('いぬ')

insert into category_source (category_name)
values ('ねこ')

insert into category_source (category_name)
values ('とり')

insert into category_source (category_name)
values ('ハムスター')

insert into category_source (category_name)
values ('りす')

insert into category_source (category_name)
values ('はちゅうるい')

insert into category_source (category_name)
values ('さかな') [42102-232]
2024-12-16 13:43:33.725188+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "STAMP_SOURCE" はすでに存在します
Table "STAMP_SOURCE" already exists; SQL statement:
create table stamp_source (
    category_id      INTEGER     generated always as identity primary key,
    category_name    VARCHAR(30)  not null default 'other'  
) [42101-232]
2024-12-16 13:43:33.727182+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "CATEGORY_SOURCE" が見つかりません
Table "CATEGORY_SOURCE" not found; SQL statement:
insert into category_source (category_name)
values ('その他')

insert into category_source (category_name)
values ('いぬ')

insert into category_source (category_name)
values ('ねこ')

insert into category_source (category_name)
values ('とり')

insert into category_source (category_name)
values ('ハムスター')

insert into category_source (category_name)
values ('りす')

insert into category_source (category_name)
values ('はちゅうるい')

insert into category_source (category_name)
values ('さかな') [42102-232]
2024-12-16 13:44:08.180671+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into category_source (category_name)\000d\000avalues ('その他')\000d\000a\000d\000a[*]insert into category_source (category_name)\000d\000avalues ('いぬ')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('ねこ')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('とり')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('ハムスター')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('りす')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('はちゅうるい')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('さかな')"
Syntax error in SQL statement "insert into category_source (category_name)\000d\000avalues ('その他')\000d\000a\000d\000a[*]insert into category_source (category_name)\000d\000avalues ('いぬ')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('ねこ')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('とり')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('ハムスター')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('りす')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('はちゅうるい')\000d\000a\000d\000ainsert into category_source (category_name)\000d\000avalues ('さかな')"; SQL statement:
insert into category_source (category_name)
values ('その他')

insert into category_source (category_name)
values ('いぬ')

insert into category_source (category_name)
values ('ねこ')

insert into category_source (category_name)
values ('とり')

insert into category_source (category_name)
values ('ハムスター')

insert into category_source (category_name)
values ('りす')

insert into category_source (category_name)
values ('はちゅうるい')

insert into category_source (category_name)
values ('さかな') [42000-232]
2024-12-16 13:49:07.003444+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "CATEGORY_SOURCE" が見つかりません
Table "CATEGORY_SOURCE" not found; SQL statement:
insert into category_source (category_name)
values
    ('その他'),
    ('いぬ'),
    ('ねこ'),
    ('とり'),
    ('ハムスター'),
    ('りす'),
    ('はちゅうるい'),
    ('さかな') [42102-232]
2024-12-19 14:39:52.825711+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-19 14:41:04.801298+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-19 14:45:48.715812+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-19 14:47:00.899760+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-19 14:47:08.985695+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
INSERT INTO TWEETS(NAME, TEXT, DATETIME, GOOD, IMAGE_URL) VALUES(?, ?, ?, ?, ?) [42102-232]
2024-12-19 15:59:36.281596+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "EMAIL" が見つかりません
Column "EMAIL" not found; SQL statement:
SELECT user_id user_name, mail_address, password FROM users WHERE email = ? [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1235)
	at org.h2.command.query.Query.prepare(Query.java:232)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:315)
	at dao.UsersDAO.findUserByEmail(UsersDAO.java:19)
	at model.LoginLogic.execute(LoginLogic.java:14)
	at servlet.Login.doPost(Login.java:30)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-19 15:59:37.955209+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "EMAIL" が見つかりません
Column "EMAIL" not found; SQL statement:
SELECT user_id user_name, mail_address, password FROM users WHERE email = ? [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1235)
	at org.h2.command.query.Query.prepare(Query.java:232)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:315)
	at dao.UsersDAO.findUserByEmail(UsersDAO.java:19)
	at model.LoginLogic.execute(LoginLogic.java:14)
	at servlet.Login.doPost(Login.java:30)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-19 15:59:49.109931+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "EMAIL" が見つかりません
Column "EMAIL" not found; SQL statement:
SELECT user_id user_name, mail_address, password FROM users WHERE email = ? [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1235)
	at org.h2.command.query.Query.prepare(Query.java:232)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:315)
	at dao.UsersDAO.findUserByEmail(UsersDAO.java:19)
	at model.LoginLogic.execute(LoginLogic.java:14)
	at servlet.Login.doPost(Login.java:30)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-19 16:00:35.602934+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "EMAIL" が見つかりません
Column "EMAIL" not found; SQL statement:
SELECT user_id user_name, mail_address, password FROM users WHERE email = ? [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:147)
	at org.h2.expression.Expression.optimizeCondition(Expression.java:148)
	at org.h2.command.query.Select.prepareExpressions(Select.java:1235)
	at org.h2.command.query.Query.prepare(Query.java:232)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:315)
	at dao.UsersDAO.findUserByEmail(UsersDAO.java:19)
	at model.LoginLogic.execute(LoginLogic.java:14)
	at servlet.Login.doPost(Login.java:30)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-19 16:01:13.877722+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-19 16:02:36.849269+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-20 10:12:14.037526+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "TWEETS" が見つかりません
Table "TWEETS" not found; SQL statement:
SELECT ID, NAME, TEXT, DATETIME, GOOD FROM TWEETS ORDER BY ID DESC [42102-232]
2024-12-20 11:30:55.774932+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TOTAL_STAMP" が見つかりません
Column "TOTAL_STAMP" not found [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at dao.PostDAO.findAll(PostDAO.java:40)
	at model.GetPostListLogic.execute(GetPostListLogic.java:11)
	at servlet.Main.doGet(Main.java:27)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-20 11:32:22.981629+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "TOTAL_STAMP" が見つかりません
Column "TOTAL_STAMP" not found [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337)
	at dao.PostDAO.findAll(PostDAO.java:40)
	at model.GetPostListLogic.execute(GetPostListLogic.java:11)
	at servlet.Main.doGet(Main.java:27)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-20 15:04:47.087944+09:00 database: flush
org.h2.message.DbException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at util.DBUtil.getConnection(DBUtil.java:13)
	at model.LoginLogic.execute(LoginLogic.java:12)
	at servlet.Login.doPost(Login.java:30)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 44 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 38 more
2024-12-23 15:16:12.941726+09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "inu_dog223" が見つかりません
Column "inu_dog223" not found; SQL statement:
INSERT INTO picture (user_id, post_id, picture_url)
 VALUES ("inu_dog223",6,"uploads/dog_1.jpg") [42122-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244)
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:299)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:489)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:645)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:561)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1164)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:245)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1344)
	at org.h2.server.web.WebApp.query(WebApp.java:1142)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1108)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1095)
	at org.h2.server.web.WebThread.process(WebThread.java:190)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-12-23 15:18:56.398801+09:00 database: flush
org.h2.message.DbException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at util.DBUtil.getConnection(DBUtil.java:13)
	at dao.PostDAO.create(PostDAO.java:44)
	at model.PostLogic.execute(PostLogic.java:17)
	at test.Main.main(Main.java:22)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
2024-12-23 15:19:45.805609+09:00 database: flush
org.h2.message.DbException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at util.DBUtil.getConnection(DBUtil.java:13)
	at dao.PostDAO.create(PostDAO.java:44)
	at model.PostLogic.execute(PostLogic.java:17)
	at test.Main.main(Main.java:22)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 一般エラー: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]" [50000-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/8Java28/Desktop/workspace/08java28_pj/DB/ikimono.mv.db [2.3.232/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 15 more
